version: '3'

services:
  pgdb:
    image: postgres:16
    expose:
      - '5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  backend:
    container_name: backend
    build: ./backend
    command: sh -c "
      python manage.py makemigrations 
      && python3 manage.py migrate
      && python manage.py loaddata postgres.json
      && gunicorn backend.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
      - django-static:/backend/static
    ports:
      - "8000:8000"
    environment:
      - DB_USER='postgres'
      - DB_PASSWORD='postgres'
      - DB_PORT:'6543'
    depends_on:
      - pgdb
  
volumes:
  django-static:
  pgdbdata: