# Generated by Django 4.2.6 on 2023-10-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transport'),
        ),
    ]
