# Generated by Django 4.2.6 on 2023-10-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_person_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canBeRented', models.BooleanField(default=True)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=6, unique=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('minutePrice', models.IntegerField(null=True)),
                ('dayPrice', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('transportType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporttype')),
            ],
        ),
    ]
